## YAML Template.
page_size: 100
service_name: alto

record_types:
    talis_soa_borrower:
        uri: http://jangle.org/vocab/formats#talis_soa_borrower
        content-type: application/xml
    talis_soa_availability:
        uri: http://jangle.org/vocab/formats#talis_soa_availability
        content-type: application/xml        
    dlfexpanded:
        uri: "http://jangle.org/vocab/formats#http://diglib.org/ilsdi/1.0"
        content-type: application/xml
    daia:
        uri: "http://jangle.org/vocab/formats#http://ws.gbv.de/daia/"
        content-type: application/xml
    vcard:
        uri: "http://jangle.org/vocab/formats#text/x-vcard"
        content-type: text/x-card
    marcxml:
        uri: "http://jangle.org/vocab/formats#http://www.loc.gov/MARC21/slim"
        content-type: application/xml
    marc:
        uri: "http://jangle.org/vocab/formats#application/marc"
        content-type: application/marc
    mods:
        uri: "http://jangle.org/vocab/formats#http://www.loc.gov/mods/v3"
        content-type: application/xml                
        stylesheets:
            feed: 
                uri: http://jangle.googlecode.com/svn/trunk/xsl/AtomMARC21slim2MODS3-2.xsl
                entities:
                    - resources
            item: 
                uri: http://www.loc.gov/standards/mods/v3/MARC21slim2MODS3-2.xsl
                entities:
                    - resources
    dc:
        uri: "http://jangle.org/vocab/formats#http://purl.org/dc/elements/1.1/"
        content-type: application/rdf+xml
        stylesheets:
            item: 
                uri: http://www.loc.gov/standards/marcxml/xslt/MARC21slim2RDFDC.xsl
                entities:
                    - resources
            feed: 
                uri: http://jangle.googlecode.com/svn/trunk/xsl/AtomMARC21slim2RDFDC.xsl
                entities:
                    - resources
    oai_dc:
        uri: "http://jangle.org/vocab/formats#http://www.openarchives.org/OAI/2.0/oai_dc/"
        content-type: application/xml    
        stylesheets:
            item: 
                uri: http://www.loc.gov/standards/marcxml/xslt/MARC21slim2OAIDC.xsl
                entities:
                    - resources
            feed: 
                uri: http://jangle.googlecode.com/svn/trunk/xsl/AtomMARC21slim2OAIDC.xsl
                entities:
                    - resources    
    atom:
        uri: "http://jangle.org/vocab/formats#http://www.w3.org/2005/Atom"
        content-type: application/atom+xml

entities:    
    actors:
        title: Borrowers
        record_types:            
            vcard: vcard.erb
            talis_soa_borrower: talis_borrower.xml.builder
        search: false
        options:
            - get
        services:
            - items
            - resources
        
    resources:
        title: Bibliographic records
        record_types:
            marcxml: marc.erb
            marc: marc.erb
            mods: marc.erb
            dc: marc.erb
            oai_dc: marc.erb            
        search:
            longname: Search Bibliographic records in OpenBiblio
            description: Bibliographic records search.  Defaults to keyword anywhere.
            tags: catalog library
            syndicationright: open
            query: thomas
            parameters:
                query: searchTerms?
                field: field?
                type: type?
                from: from?
                until: until?
                count: count?
                startIndex: startIndex?                
        options:
            - get
        services:
            - items
            - collections
        
    items:
        title: Holdings records
        record_types:            
            dlfexpanded: dlfexpanded.xml.builder
            #talis_soa_availability: talis_availability.xml.builder
            #daia: daia.xml.builder
        search: false
        options:
            - get
        services:
            - resources
            - actors
    collections:
        title: Categories
        record_types:
            dc: dc.xml.builder
        search: false
        options:
            - get
        services:
            - resources            
        
